# Generated by Django 4.1.6 on 2023-02-20 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='contact_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='sl_no',
            field=models.IntegerField(),
        ),
    ]
