# Generated by Django 4.1.6 on 2023-02-20 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importapp', '0002_alter_alumni_contact_no_alter_alumni_sl_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='sl_no',
            field=models.IntegerField(null=True),
        ),
    ]
