# Generated by Django 4.1.6 on 2023-02-20 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importapp', '0003_alter_alumni_sl_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumni',
            name='sl_no',
        ),
        migrations.AlterField(
            model_name='alumni',
            name='contact_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='usn',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
